//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class birey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public birey()
        {
            this.doktor = new HashSet<doktor>();
            this.kullanicilar = new HashSet<kullanicilar>();
        }
    
        public int id { get; set; }
        public int tckimlikno { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string dogumyeri { get; set; }
        public Nullable<System.DateTime> dtarihi { get; set; }
        public string cinsiyet { get; set; }
        public string kangrubu { get; set; }
        public string medenihal { get; set; }
        public string anneadi { get; set; }
        public string babaadi { get; set; }
        public string evtel { get; set; }
        public string ceptel { get; set; }
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doktor> doktor { get; set; }
        public virtual hasta hasta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanicilar> kullanicilar { get; set; }
    }
}
