//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cikis
    {
        public int dosyaID { get; set; }
        public string sevkTarihi { get; set; }
        public Nullable<System.DateTime> cikisSaati { get; set; }
        public string odeme { get; set; }
        public string toplamtutar { get; set; }
    }
}
