//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hasta()
        {
            this.dosya = new HashSet<dosya>();
        }
    
        public long tckimlikno { get; set; }
        public int dosyaID { get; set; }
        public string kurumsicilno { get; set; }
        public string kurumadi { get; set; }
        public string yakintel { get; set; }
        public string yakinkurumsicilno { get; set; }
        public string yakinkurumadi { get; set; }
    
        public virtual birey birey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dosya> dosya { get; set; }
    }
}
