//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemler
    {
        public int id { get; set; }
        public System.DateTime sevktarihi { get; set; }
        public int islemid { get; set; }
        public Nullable<int> doktorid { get; set; }
    
        public virtual doktor doktor { get; set; }
        public virtual islem islem { get; set; }
        public virtual sevk sevk { get; set; }
    }
}
