//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int id { get; set; }
        public long tckimlikno { get; set; }
        public string username { get; set; }
        public string sifre { get; set; }
        public string yetki { get; set; }
        public string unvan { get; set; }
        public Nullable<System.DateTime> isebaslama { get; set; }
        public string maas { get; set; }
    
        public virtual birey birey { get; set; }
    }
}
