//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class poliklinik
    {
        public string poliklinikadi { get; set; }
        public string durum { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> bolumid { get; set; }
    
        public virtual poliklinik_isim poliklinik_isim { get; set; }
        public virtual poliklinik poliklinik1 { get; set; }
        public virtual poliklinik poliklinik2 { get; set; }
    }
}
