//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class poliklinik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poliklinik()
        {
            this.sevk = new HashSet<sevk>();
        }
    
        public string poliklinikadi { get; set; }
        public string durum { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> bolumid { get; set; }
    
        public virtual poliklinik_isim poliklinik_isim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sevk> sevk { get; set; }
    }
}
