//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sağlık_Ocağı_HTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class sevk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sevk()
        {
            this.islemler = new HashSet<islemler>();
            this.sevkler = new HashSet<sevkler>();
        }
    
        public System.DateTime sevktarihi { get; set; }
        public Nullable<int> sevkedendoktorid { get; set; }
        public string poliklinik { get; set; }
        public string sira { get; set; }
        public string saat { get; set; }
        public Nullable<int> taburcuid { get; set; }
    
        public virtual doktor doktor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemler> islemler { get; set; }
        public virtual poliklinik poliklinik1 { get; set; }
        public virtual taburcu taburcu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sevkler> sevkler { get; set; }
    }
}
